---
title: "What softwares do I actually use on my Mac as a software enthusiast?"
date: 2023-07-25
display-date: Jul 2023
format: html
categories: [Tools, MacOS, Softwares]
filters:
  - collapse-social-embeds
  - lightbox
draft: false
reference-location: margin
citation-location: margin
lightbox: auto
description: MacOS softwares are a huge thing of their own. They have a pretty great developer ecosystem, so there are many great indie apps that are awesome to know about, especially if you are just starting your MacOS journey.
---

On a daily basis, I use multiple apps and I prefer to put them together here. In general, I am always looking for better note-taking apps, and if you have any suggestions, I would love to know (trust me, I have tried 800 of them!). I will divide this into different categories of software I use, in case they are helpful for anyone.

```{=html}
<!-- ::: callout-important
## Incomplete Post

This is incomplete and I will be filling it over the next few weeks.
::: -->
```
For some context, I use a M1 Pro, Macbook Pro, with 16GB RAM and 512GB SSD. Some of these applications might not be great on 8GB RAM or 128GB SSD, so proceed with discretion.

# Productivity Software

-   **Communication**: [Spark Email 2](https://sparkmailapp.com/spark2) is my email client of choice rather than using the general Apple mail client. Why? Because it has the ability to remove Updates/Promotions/Forums from my main inbox that Apple mail does not. It also does basic Newsletters and Pins options for each email account, that Apple mail does not. To have all the DMs in one place, I use [Texts](https://texts.com/). If you do not have multiple accounts per app, you can also use [Beeper](https://www.beeper.com/).

-   **Tasks**: I use [Todoist](https://todoist.com/). I have used 100 other apps, but I keep coming back to Todoist. With their quick capture being all bang based, nothing is easier for me to quick capture, schedule, rescheduled, completed. It syncs with Google Calendar. It works in collaboration mode. This is the only task tracker that has worked for me.

-   **Terminal**: [Warp](https://www.warp.dev/) as terminal. I do not work with vim, so take my advice with a grain of salt. But I really like block based terminals. It also has a bang based AI mode. You can type `#` to ask it to provide the command that `converts all images in this folder and sub-folders to .webp and delete the original versions` and it will provide you with the command with templated tab-able arguments.

-   **Sticky Notes**: [Numi](https://numi.app/) is the app I use for pasting on always on top notes. It is also great for calculations inside notes. It is extremely expensive, so probably get it on sale rather than anytime else, would be my recommendation.

-   **Calendar and Timers**: [Dato](https://apps.apple.com/us/app/dato/id1470584107) is for calendar and meetings. It shows the meeting time and current time across timezones, shows a monthly calendar, has an option to join a meeting from the menu bar. The reason I use it over [itsycal](https://www.mowglii.com/itsycal/) is for its full screen notifications because I otherwise forget the meeting time or join a minute or two late. If you do not need that or timezones, itsycal is free and does everything else. I also use [Day Progress](https://apps.apple.com/us/app/day-progress/id6450280202) because I am time-blind, but most people would not need it. I use [Timer RH](https://apps.apple.com/us/app/red-hot-timer/id929960914) for always on top timers for timed tasks. It connects with the calendar as well, is pretty easy to set rather than using a Siri command (just drag the menu bar icon down to however long you need the timer to be).

-   **Note taking**: I use [Aiko](https://apps.apple.com/us/app/aiko/id1672085276) at the moment for transcription of my blabberings, [Tactiq](https://app.tactiq.io/) for remote meetings, and [Otter](https://otter.ai/) for in person meetings. For long form note taking, I use [Notion](https://www.notion.so/) at the moment, but it is not necessarily my tool of choice, given its poor AI integration that would allow me to go from unstructured to structured content. It also lacks a calendar integration and spatial system, so I am always on a lookout for something different. Some other softwares I am exploring are [Tana](https://tana.inc/) (better AI and API integration), [Capacities](https://capacities.io/) (no collaboration), [Heptabase](https://heptabase.com/) (no collaboration) and [Google Workspace](https://workspace.google.com/products/docs/) (no block based editing but has newly added chips, task management, linking previews etc). I use [Goodnotes](https://www.goodnotes.com/) or [Apple Notes](https://apps.apple.com/us/app/notes/id1110145109) for handwritten note taking.

-   **Reference management**: I used to use [Paperpile](https://paperpile.com/) but I shifted to using Notion for this purpose because I could not make use of the highlighted information. I use either [ar5iv](https://ar5iv.labs.arxiv.org/) or [Paper To HTML](https://papertohtml.org/) to snip papers into notion.

-   **Whiteboarding**: I use [Guga](https://www.guga.co/) (new app, chinese support) or [Muse](https://museapp.com/) (expensive but works really well, has a teams version). I tried [Freeform](https://apps.apple.com/us/app/freeform/id6443742539) and did not like it much. Guga also does not have desktop support which kinda hampers its usage on my end.

-   **Reading**: I use [Reader from Readwise](https://readwise.io/read), they allow you to annotate pdfs, videos webpages, add highlights, add notes to highlights etc. It is cheap for students; syncs highlights from everywhere to Notion and works reliably. The two other options are [Omnivore](https://omnivore.app/) (open source and free) and [Matter](https://hq.getmatter.com/) (better and more intuitive design but does not work with pdfs or videos). For podcasts, because apparently the information now also comes from podcasts, I use [Snipd](https://www.snipd.com/), which has headphone button based sniping, AI snip boundaries and snip summaries, and also syncs to Readwise or separately to Notion.

# Creative Work

I divide creative work into 2 parts, sometimes overlapping, creative work as an hobby, creative work for my research.

-   **Flowcharts**: [Whimsical](https://whimsical.com/) and [flowchart.fun](flowchart.fun). Whimsical is great for making beautiful handmade flowcharts or making flowcharts easily using AI. Flowchart.fun provides a simple language to create flowcharts by just writing text.
-   **Screenshots**: [Shottr](https://shottr.cc/) allows to create annotated screenshots, blur parts of image on device. It also allows for rolling screenshots where if you capture an area it will auto scroll the webpage or any other document for you. Shottr is free and is extremely cheap for pro version (which is only needed for not getting pinged for updating after 30 days). I use [pika](https://pika.style/) for pretty backgrounds around screenshots.
-   **Screen recordings**: Explaining a coding process or a step-by-step guide on about how to do something, we often end up with full screen videos with tiny text. I use [screen.studio](screen.studio) or [screenrun](https://screenrun.app/) for automatic zoom ins into where I am clicking or typing. Screenrun can also do a short video from a screenshot if you want to say, oh, click here and then here and then here.
-   **Paper diagrams**: [draw.io](draw.io) for making neural network diagrams. There is unfortunately nothing that comes close. I cannot do TikZ, but if you can, more power to you!
-   **Drawing**: I use [Procreate](https://procreate.com/) or [Concepts](https://concepts.app/en/). Procreate allows for really intuitive drawing interface whereas concepts is vector based, and still allows for all the flair with layers, brushes, objects etc.

# Works in Background

-   **Memory**: [Rewind.ai](Rewind.ai) has been a life-saver for me, it records everything on screen, and records laptop audio and mic if you choose to. It has two main things: search rewind and ask rewind. Search rewind is a simple keyword search over everything that has been stored. Ask rewind sends everything in those clips to OpenAI (possibly GPT3.5 16k) to create a summary and adds "screenshot" references.

-   **Shortcuts**: [Raycast](https://www.raycast.com/) allows for doing so many things that I do not know how to describe it. It is local first and is free. It also has a pro subscription if you need its AI chat options (which comes with a student discount). The best way I have seen it described is Spotlight++ but I never used spotlight. You can use `⌘+Space` to do calculations, timezone conversions, unit conversions, quick word lookup, file search, screenshot search etc.

    ::: callout-tip
    ## Amphetamine and Other Menu Bar Apps

    You can also remove the amphetamine software you have and use the menu bar coffee app that Raycast provides. It comes with many extensions, such as, hypersonic that can connect to any notion database of yours to show tasks, schedule them etc, all from `⌘+Space` or from your menu bar.

    Another menu bar app that I use from Raycast is Text Shortcuts which allows you to select any task, and convert case, URL encode and decode, convert to markdown, find text statistics (word counter, character counter) etc.
    :::

-   **Camera**: This is a small software, but I have cats, and I have messy hair. I use [Camera Preview](https://apps.apple.com/app/id1632827132) a ton both for checking on myself and using the return key to click photos. [Hand mirror](https://handmirror.app/) is the alternate option, but it cannot click photos.

-   **Utilities**: I use [Bartender](https://www.macbartender.com/) for arranging my menu bar, especially with that notch on Macbook pro. I use [Better Touch Tool](https://folivora.ai/) to assign taps to clicks (for example three finger tap to open in a new tab). I also use it to assign hyperkey. Hyperkey is when you press all meta keys together on the keyboard. For example, Hyperkey+A is my shortcut for quick task in Todoist. I use [WeatherX](https://apps.apple.com/us/app/id1662213547) to have weather of 4 cities be readily accessible in the menu bar. I use [Command+X](https://apps.apple.com/us/app/command-x/id6448461551) to have a cut option in MacOS.

-   **AI Chat Interfaces**: I use [Bolt AI](https://boltai.app/) at the moment to organize my conversations, especially those that need to go through API for non-training purposes. There are 100 such apps, this is the one I found the earliest. If I do end up paying for [Raycast Pro](https://www.raycast.com/pro), then I would not need this app. I use Bolt because, it does not show up in dock, allows to select models per chat, allows to set shortcut to bring it up. I sometimes use [Sider](https://chatgpt-sidebar.com/) (on browser) and [MacGPT](https://www.macgpt.com/) (quick question - synonym for X) too.