---
title: "My support network throughout my PhD journey"
date: 2023-08-31
date-modified: 2023-09-06
display-date: Aug 2023
format: html
categories: [Life, Academia]
filters:
  - collapse-social-embeds
  - lightbox
draft: false
reference-location: margin
citation-location: margin
lightbox: auto
description: My PhD journey wasn't easy, and a lot happened over the six years, but I made it through. The credit for that goes to all the people who supported me through this time, to whom I am forever indebted.
---

## Thesis Committee

I would like to start by expressing my profound gratitude towards my PhD advisor, [Emily *(Emily Mower Provost)*](https://emp.engin.umich.edu/). She has been my go-to person for any research brainstorming and has shown me tremendous patience, support, and guidance throughout my PhD journey. Without her persistence and suggestions, completing this PhD would not have been possible. I am also incredibly grateful for my thesis committee members: [Vinod *(VG Vinod Vydiswaran)*](http://www-personal.umich.edu/~vgvinodv/), [Nikola *(Nikola Banovic)*](http://www.nikolabanovic.net/), [Benjamin *(Benjamin Fish)*](https://ben.fish/), and [Douwe *(Douwe Kiela)*](https://douwekiela.github.io/). Their valuable insights during my thesis proposal helped shape the final version of the thesis.

## Family

For putting up with me during my PhD journey, my immense gratitude goes towards my family, especially my parents, grandparents, and [Bert](life_photo_album.qmd). My parents have been a rock for me over the past six years. Though I could not visit them often or talk to them much, they were always there when I needed someone. They seem to have aged fifteen years in the six years of my PhD, stressed about me, but their support never wavered. My mom (Archana Kumari) received her own PhD in 2021, and my dad (Abhay Kumar) became the Vice-Chancellor of a new IIIT---two accomplishments that were their lifelong dreams and inspired me immensely. I unfortunately lost two of my grandparents during the PhD program, and I will never forget their blessings and excitement for me embarking on my higher education journey. During early 2020, in the midst of COVID, I adopted a cat named Bert---yes, named after the language model. Without him, I would not have maintained my sanity during the dark, lonely nights and tiring, long work days. His purring loudly into my ear calmed me down on the worst of nights.

## Mentors

I was lucky enough to secure three internships and have amazing research mentors for all of them. [Ahmad *(Ahmad Beirami)*](https://sites.google.com/view/beirami) taught me how to approach Conversational AI, how to create effective presentations, and how to write research proposals. [Adina *(Adina Williams)*](https://wp.nyu.edu/adinawilliams/) a taught me how to work with linguistics mixed in with NLP, and how subjectivity can infiltrate seemingly objective parts (like NLI) of NLP. [Ana *(Ana Marasović)*](https://www.anamarasovic.com/) was the first person I worked with on really large language models (foundational models), and she taught me how to approach evaluation and benchmarking for generative models---a major part of my current research path.

## Lab Members

I want to thank my lab members, starting with [Zak *(Zakaria Aldeneh)*](https://www.linkedin.com/in/zakaria-aldeneh). Zak exemplifies what all senior PhD mentors should be, helping me with code, brainstorming, and working with me on papers. He has been an amazing research collaborator. I also want to thank Minxue *(Minxue Sandy Niu)* for being the junior research collaborator anyone would be proud of. She has not only been an amazing collaborator but was also always willing to discuss interesting research problems. I want to thank [Matt *(Matthew Perez)*](https://matthewkperez.com/) for being the batchmate who has always been there to help, to vent, to advise, and to collaborate, serving as my go-to person for any speech-based research questions. Finally, I want to thank [Amrit *(Amrit Romana)*](http://www-personal.umich.edu/~aromana/) for being an amazing lab member; her observant questions helped me immensely during lab presentations.

## Friends

I also want to thank my friends, without whom this journey would not have been possible. I will start with [Abhinav *(Abhinav Jangda)*](https://sites.google.com/site/abhijangda/), who has been my support system throughout my PhD journey, starting from the application process. [Diksha *(Diksha Dhawan)*](https://www.linkedin.com/in/dhawandiksha/) was the best PhD roommate one could ask for during the first four years of my PhD. She shared laughter and tears with me, cooked with me, and supported me through all the highs and lows. Without her, I could not have survived my PhD. She taught me the value of being proud of my interests in both my personal and professional life, and how friends can sometimes be family, which is the best gift anyone could have given me. [Eesh (Sudheesh Srivastava)](https://www.linkedin.com/in/sudheesh-srivastava-formal/), for all the conversations at the intersection of machine learning, physics, and philosophy, has taught me about areas and theories that I would have otherwise not encountered in any way or format. Conversations with him have always left me rejuvenated, happy, and feeling peppier---a testament to how amazing a best friend he is. [Sagarika *(Sagarika Srishti)*](https://www.linkedin.com/in/sagarika-srishti/), for all her support, both in India and when she came to the US. Her move to the US during my PhD was a major personal highlight. [Ariba *(Ariba Javed)*](https://www.linkedin.com/in/ariba-javed-uofm/), thanks for all the discussions, talks, and emotional conversations, and for always being up for anything interesting, including a pottery class. [Shobhit *(Shobhit Narain)*](https://www.linkedin.com/in/shobhit-narain/) has been an amazing companion, helping me with job applications and always being the sarcastic, serious, yet most helpful guy I have had the pleasure of calling a friend. And finally, Sai *(Sairam Tabibu)* helped me fill out the PhD application for UMich on the exact deadline, without which, I would not be here at all.

## Streaming and Gaming Community

This is probably an unconventional paragraph in acknowledgments, but these were unconventional times during COVID. For the two years of lockdown, I turned to Among Us when I felt lonely or lost in my research. I am really thankful for the streamers whose broadcasts provided some semblance of social interaction. For almost three years, I watched them stream at least 8 hours a day while I worked, to simulate a social environment. And when my research progress stalled, I turned to anonymous Discord communities, playing Among Us and golf for hours, which helped alleviate feelings of depression and sadness, providing a much-needed uplift.

## tl;dr

My PhD journey wasn't easy, and a lot happened over the six years, but I made it through. The credit for that goes to all the people mentioned here, to whom I am forever indebted.